import { Injectable, NotFoundException } from "@nestjs/common";
import { PassportVerificationStatus } from "@prisma/client";
import { PrismaService } from "@/prisma/prisma.service";
import { EventBusService } from "@/core/event-bus.service";
import { RiskEngineService } from "@/core/risk-engine.service";
import { toInputJsonValue } from "@/common/utils/json.util";
import { SearchPassportsDto } from "@/modules/passports/dto/search-passports.dto";

@Injectable()
export class PassportsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly eventBus: EventBusService,
    private readonly riskEngine: RiskEngineService
  ) {}

  list(query: SearchPassportsDto) {
    return this.prisma.digitalProductPassport.findMany({
      where: {
        organizationId: query.organizationId ?? undefined,
        productId: query.productId ?? undefined
      },
      include: {
        product: {
          include: {
            brand: true
          }
        },
        circularId: true,
        manufacturer: true,
        sustainabilityScores: {
          orderBy: { createdAt: "desc" },
          take: 1
        }
      },
      orderBy: { updatedAt: "desc" },
      take: 100
    });
  }

  async getOne(code: string) {
    const passport = await this.prisma.digitalProductPassport.findFirst({
      where: {
        OR: [{ passportCode: code }, { circularId: { code } }]
      },
      include: {
        product: {
          include: {
            brand: true
          }
        },
        circularId: true,
        manufacturer: true,
        sustainabilityScores: {
          orderBy: { createdAt: "desc" },
          take: 5
        }
      }
    });

    if (!passport) {
      throw new NotFoundException("Digital product passport not found.");
    }

    return passport;
  }

  async ensureForProduct(productId: string) {
    const existing = await this.prisma.digitalProductPassport.findFirst({
      where: { productId },
      include: {
        product: {
          include: {
            brand: true,
            circularIds: true
          }
        }
      }
    });

    if (existing) {
      return existing;
    }

    const product = await this.prisma.product.findUnique({
      where: { id: productId },
      include: {
        brand: true,
        circularIds: true
      }
    });
    if (!product) {
      throw new NotFoundException("Product not found.");
    }

    const circularId = product.circularIds[0] ?? null;
    const scores = this.riskEngine.computeImpactScore({
      materialsScore: Math.max(60, product.sustainabilityScore - 4),
      emissionsScore: Math.max(50, 100 - product.carbonScore / 1.2),
      transportScore: 72,
      recyclabilityScore: product.repairabilityScore,
      durabilityScore: product.repairabilityScore
    });

    const passport = await this.prisma.digitalProductPassport.create({
      data: {
        organizationId: product.brand.organizationId,
        productId: product.id,
        circularIdId: circularId?.id,
        passportCode: `DPP-AUTO-${product.sku}`,
        materialComposition: toInputJsonValue(product.materials),
        manufacturingOrigin: product.origin,
        supplierChain: toInputJsonValue({
          autogenerated: true,
          nodes: [
            {
              name: product.brand.name,
              role: "brand"
            }
          ]
        }),
        environmentalImpact: toInputJsonValue(scores.categoryBreakdown),
        lifecycleData: toInputJsonValue({
          lifecycleState: circularId?.lifecycleState ?? "active",
          generatedAt: new Date().toISOString()
        }),
        verificationStatus: PassportVerificationStatus.VERIFIED
      }
    });

    await this.prisma.sustainabilityScore.create({
      data: {
        organizationId: product.brand.organizationId,
        productId: product.id,
        passportId: passport.id,
        normalizedScore: scores.normalizedScore,
        transparencyConfidence: scores.transparencyConfidence,
        materialsScore: scores.categoryBreakdown.materialsScore,
        emissionsScore: scores.categoryBreakdown.emissionsScore,
        transportScore: scores.categoryBreakdown.transportScore,
        recyclabilityScore: scores.categoryBreakdown.recyclabilityScore,
        durabilityScore: scores.categoryBreakdown.durabilityScore,
        categoryBreakdown: toInputJsonValue(scores.categoryBreakdown)
      }
    });

    this.eventBus.emit("passport_generated", {
      productId: product.id,
      passportCode: passport.passportCode
    });

    return this.getOne(passport.passportCode);
  }
}
